# generated by datamodel-codegen:
#   filename:  doc.json
#   timestamp: 2023-05-27T20:43:24+00:00

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel


class Producer(BaseModel):
    name: str
    abbr: str
    affiliation: str
    role: str


class MetadataInformation(BaseModel):
    title: str
    idno: str
    producers: List[Producer]
    production_date: str
    version: str


class TitleStatement(BaseModel):
    idno: str
    title: str
    sub_title: str
    alternate_title: str
    translated_title: str


class AuthorIdItem(BaseModel):
    type: None
    id: None


class Author(BaseModel):
    first_name: str
    initial: str
    last_name: str
    affiliation: str
    author_id: List[AuthorIdItem]
    full_name: str


class Editor(BaseModel):
    first_name: str
    initial: str
    last_name: str
    affiliation: str


class Identifier(BaseModel):
    type: str
    identifier: str


class TocStructuredItem(BaseModel):
    id: str
    parent_id: str
    name: str


class Note(BaseModel):
    note: str


class RefCountryItem(BaseModel):
    name: str
    code: str


class GeographicUnit(BaseModel):
    name: str
    code: str
    type: str


class BboxItem(BaseModel):
    west: str
    east: str
    south: str
    north: str


class Language(BaseModel):
    name: str
    code: str


class LicenseItem(BaseModel):
    name: str
    uri: str


class BibliographicCitationItem(BaseModel):
    style: str
    citation: str


class Translator(BaseModel):
    first_name: str
    initial: str
    last_name: str
    affiliation: str


class Contributor(BaseModel):
    first_name: str
    initial: str
    last_name: str
    affiliation: str
    contribution: str


class Contact(BaseModel):
    name: str
    role: str
    affiliation: str
    email: str
    telephone: str
    uri: str


class Source(BaseModel):
    source_origin: str
    source_char: str
    source_doc: str


class DataSource(BaseModel):
    name: str
    uri: str
    note: str


class Keyword(BaseModel):
    name: str
    vocabulary: str
    uri: str


class Theme(BaseModel):
    id: str
    name: str
    parent_id: str
    vocabulary: str
    uri: str


class Topic(BaseModel):
    id: str
    name: str
    parent_id: str
    vocabulary: str
    uri: str


class Discipline(BaseModel):
    id: str
    name: str
    parent_id: str
    vocabulary: str
    uri: str


class Relation(BaseModel):
    name: str
    type: str


class Link(BaseModel):
    uri: str
    description: str


class Reproducibility(BaseModel):
    statement: str
    links: List[Link]


class DocumentDescription(BaseModel):
    title_statement: TitleStatement
    authors: List[Author]
    editors: List[Editor]
    date_created: str
    date_available: str
    date_modified: str
    date_published: str
    identifiers: List[Identifier]
    type: str
    status: str
    description: str
    toc: str
    toc_structured: List[TocStructuredItem]
    abstract: str
    notes: List[Note]
    scope: str
    ref_country: List[RefCountryItem]
    geographic_units: List[GeographicUnit]
    bbox: List[BboxItem]
    spatial_coverage: str
    temporal_coverage: str
    publication_frequency: str
    languages: List[Language]
    license: List[LicenseItem]
    bibliographic_citation: List[BibliographicCitationItem]
    chapter: str
    edition: str
    institution: str
    journal: str
    volume: str
    number: str
    pages: str
    series: str
    publisher: str
    publisher_address: str
    annote: str
    booktitle: str
    crossref: str
    howpublished: str
    key: str
    organization: str
    url: None
    translators: List[Translator]
    contributors: List[Contributor]
    contacts: List[Contact]
    rights: str
    copyright: str
    usage_terms: str
    disclaimer: str
    security_classification: str
    access_restrictions: str
    sources: List[Source]
    data_sources: List[DataSource]
    keywords: List[Keyword]
    themes: List[Theme]
    topics: List[Topic]
    disciplines: List[Discipline]
    audience: str
    mandate: str
    pricing: str
    relations: List[Relation]
    reproducibility: Reproducibility


class OriginDescription(BaseModel):
    harvest_date: str
    altered: bool
    base_url: str
    identifier: str
    date_stamp: str
    metadata_namespace: str


class ProvenanceItem(BaseModel):
    origin_description: OriginDescription


class Tag(BaseModel):
    tag: str
    tag_group: str


class ModelInfoItem(BaseModel):
    source: str
    author: str
    version: str
    model_id: str
    nb_topics: int
    description: str
    corpus: str
    uri: str


class TopicWord(BaseModel):
    word: str
    word_weight: int


class TopicDescriptionItem(BaseModel):
    topic_id: None
    topic_score: None
    topic_label: str
    topic_words: List[TopicWord]


class LdaTopic(BaseModel):
    model_info: List[ModelInfoItem]
    topic_description: List[TopicDescriptionItem]


class Embedding(BaseModel):
    id: str
    description: str
    date: str
    vector: None


class Model(BaseModel):
    repositoryid: str
    published: int
    overwrite: str
    metadata_information: MetadataInformation
    document_description: DocumentDescription
    provenance: List[ProvenanceItem]
    tags: List[Tag]
    lda_topics: List[LdaTopic]
    embeddings: List[Embedding]
    additional: Dict[str, Any]
